<a href="https://colab.research.google.com/github/malak-mahdaoui/Data-Analytics-and-Business-Intelligence/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


data = pd.read_csv('/content/train.csv')

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
data.shape[1]

18

In [ ]:
data.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9796,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9797,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum(1)

0       0
1       0
2       0
3       0
4       0
       ..
9795    0
9796    0
9797    0
9798    0
9799    0
Length: 9800, dtype: int64

In [ ]:
data.isnull().sum(axis=0)#11 colone null pour le code postal

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [ ]:
data_droped=data.dropna()#eliminer tous les ligne qui a o- une ligne vide

In [ ]:
data_droped.isnull().sum()#tjr donner un nom pour ne perdre pas mon data

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [ ]:
data.isnull().sum(axis=0)

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [ ]:
data.head(10)#pour afficher les ligne que vue

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
8,9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040
9,10,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000

In [ ]:
data.iloc[10]#affch les ligne qui je dmnd

Row ID                                                 11
Order ID                                   CA-2015-115812
Order Date                                     09/06/2015
Ship Date                                      14/06/2015
Ship Mode                                  Standard Class
Customer ID                                      BH-11710
Customer Name                             Brosina Hoffman
Segment                                          Consumer
Country                                     United States
City                                          Los Angeles
State                                          California
Postal Code                                       90032.0
Region                                               West
Product ID                                FUR-TA-10001539
Category                                        Furniture
Sub-Category                                       Tables
Product Name     Chromcraft Rectangular Conference Tables
Sales                                            1706.184
Name: 10, dtype: object

In [ ]:
data.nunique()

Row ID           9800
Order ID         4922
Order Date       1230
Ship Date        1326
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              529
State              49
Postal Code       626
Region              4
Product ID       1861
Category            3
Sub-Category       17
Product Name     1849
Sales            5757
dtype: int64

In [ ]:
grouped = data.groupby('Order Date')['sales'].mean(numeric_only=True)
print(grouped)


highest_avg_row = grouped.mean(axis=1).idxmax()
print("Row with Highest Average:\n", grouped.loc[highest_avg_row])

KeyError: 'Column not found: sales'

In [ ]:
data.groupby('Order Date')[['Sales']].mean(numeric_only=True)

                 Sales
Order Date
01/01/2018  148.182800
01/02/2015  468.900000
01/02/2017   80.985000
01/03/2015  220.315100
01/03/2016  234.596343
...                ...
31/10/2017  468.812375
31/10/2018  174.642667
31/12/2015  375.233571
31/12/2016  125.576727
31/12/2017  104.538286

[1230 rows x 1 columns]

In [ ]:
columns_order = ['Order ID', 'Order Date', 'Sales', 'Product ID', 'Category', 'Sub-Category'] + [col for col in data.columns if col not in ['Order ID', 'Order Date', 'Sales', 'Product ID', 'Category', 'Sub-Category']]
data[columns_order]#en vas saiser les colone sellon les colone influence

,Order ID,Order Date,Sales,Product ID,Category,Sub-Category,Row ID,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product Name
0,CA-2017-152156,08/11/2017,261.9600,FUR-BO-10001798,Furniture,Bookcases,1,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,Bush Somerset Collection Bookcase
1,CA-2017-152156,08/11/2017,731.9400,FUR-CH-10000454,Furniture,Chairs,2,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,CA-2017-138688,12/06/2017,14.6200,OFF-LA-10000240,Office Supplies,Labels,3,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,Self-Adhesive Address Labels for Typewriters b...
3,US-2016-108966,11/10/2016,957.5775,FUR-TA-10000577,Furniture,Tables,4,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Bretford CR4500 Series Slim Rectangular Table
4,US-2016-108966,11/10/2016,22.3680,OFF-ST-10000760,Office Supplies,Storage,5,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Eldon Fold 'N Roll Cart System
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,CA-2017-125920,21/05/2017,3.7980,OFF-BI-10003429,Office Supplies,Binders,9796,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,"Cardinal HOLDit! Binder Insert Strips,Extra St..."
9796,CA-2016-128608,12/01/2016,10.3680,OFF-AR-10001374,Office Supplies,Art,9797,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,"BIC Brite Liner Highlighters, Chisel Tip"
9797,CA-2016-128608,12/01/2016,235.1880,TEC-PH-10004977,Technology,Phones,9798,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,GE 30524EE4
9798,CA-2016-128608,12/01/2016,26.3760,TEC-PH-10000912,Technology,Phones,9799,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,Anker 24W Portable Micro USB Car Charger
9799,CA-2016-128608,12/01/2016,10.3840,TEC-AC-10000487,Technology,Accessories,9800,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,SanDisk Cruzer 4 GB USB Flash Drive

In [ ]:
for col in data.select_dtypes(include='number').columns:
    data[col] = data[col].astype(float)

In [ ]:
data.applymap(lambda x: x.lower() if type(x) == str else x)

<ipython-input-8-ba00868baae8>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data.applymap(lambda x: x.lower() if type(x) == str else x)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,sale interest
0,1,ca-2017-152156,08/11/2017,11/11/2017,second class,cg-12520,claire gute,consumer,united states,henderson,kentucky,42420.0,south,fur-bo-10001798,furniture,bookcases,bush somerset collection bookcase,0.011571,1
1,2,ca-2017-152156,08/11/2017,11/11/2017,second class,cg-12520,claire gute,consumer,united states,henderson,kentucky,42420.0,south,fur-ch-10000454,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",0.032332,1
2,3,ca-2017-138688,12/06/2017,16/06/2017,second class,dv-13045,darrin van huff,corporate,united states,los angeles,california,90036.0,west,off-la-10000240,office supplies,labels,self-adhesive address labels for typewriters b...,0.000646,1
3,4,us-2016-108966,11/10/2016,18/10/2016,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,florida,33311.0,south,fur-ta-10000577,furniture,tables,bretford cr4500 series slim rectangular table,0.042299,1
4,5,us-2016-108966,11/10/2016,18/10/2016,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,florida,33311.0,south,off-st-10000760,office supplies,storage,eldon fold 'n roll cart system,0.000988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4817,4818,ca-2015-139598,26/12/2015,31/12/2015,standard class,mg-17695,maureen gnade,consumer,united states,philadelphia,pennsylvania,19134.0,east,off-ap-10003287,office supplies,appliances,tripp lite tlp810net broadband surge for modem...,0.003602,1
4818,4819,ca-2015-139598,26/12/2015,31/12/2015,standard class,mg-17695,maureen gnade,consumer,united states,philadelphia,pennsylvania,19134.0,east,off-st-10001370,office supplies,storage,sensible storage wiretech storage systems,0.010033,1
4819,4820,ca-2018-117436,08/06/2018,14/06/2018,standard class,lw-17125,liz willingham,consumer,united states,norwich,connecticut,6360.0,east,off-bi-10004040,office supplies,binders,wilson jones impact binders,0.000458,1
4820,4821,ca-2016-140025,07/04/2016,11/04/2016,standard class,pf-19120,peter fuller,consumer,united states,san antonio,texas,78207.0,central,off-ap-10002651,office supplies,appliances,hoover upright vacuum with dirt cup,0.020463,1
4821,4822,ca-2016-140025,07/04/2016,11/04/2016,standard class,pf-19120,peter fuller,consumer,united states,san antonio,texas,78207.0,central,tec-ac-10002402,technology,accessories,razer kraken pro over ear pc and music headset,0.016918,1

In [ ]:
def sale_interest(Sale):
    if Sale < 100:
        return 1
    elif Sale < 500:
        return 2
    else:
        return 3

data['sale interest'] = data['Sales'].apply(sale_interest)
print(data['sale interest'])

0       1
1       1
2       1
3       1
4       1
       ..
4817    1
4818    1
4819    1
4820    1
4821    1
Name: sale interest, Length: 4822, dtype: int64

In [ ]:
max_sale=data['Sales'].max()
pd.cut(data['Sales'],bins=[0,max_sale/3,2*max_sale/3,max_sale],labels=[1,2,3])

0       1
1       1
2       1
3       1
4       1
       ..
9795    1
9796    1
9797    1
9798    1
9799    1
Name: Sales, Length: 9800, dtype: category
Categories (3, int64): [1 < 2 < 3]

In [ ]:
print( data['Sales'] / data['Sales'].max())

0       0.011571
1       0.032332
2       0.000646
3       0.042299
4       0.000988
          ...
4817    0.003602
4818    0.010033
4819    0.000458
4820    0.020463
4821    0.016918
Name: Sales, Length: 4822, dtype: float64

In [ ]:
 data['Sales'] / data['Sales'].max()

0       0.011571
1       0.032332
2       0.000646
3       0.042299
4       0.000988
          ...
4817    0.003602
4818    0.010033
4819    0.000458
4820    0.020463
4821    0.016918
Name: Sales, Length: 4822, dtype: float64

In [ ]:
data.drop_duplicates()#supp tous les lignes qui a des valeur mem dans tous col

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1.0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,3.0,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4.0,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,6.0,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
12,13.0,CA-2018-114412,15/04/2018,20/04/2018,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9786,9787.0,US-2015-114377,05/11/2015,05/11/2015,Same Day,BG-11035,Barry Gonzalez,Consumer,United States,Hampton,Virginia,23666.0,South,FUR-CH-10004754,Furniture,Chairs,"Global Stack Chair with Arms, Black",149.9000
9787,9788.0,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-BO-10001811,Furniture,Bookcases,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.3320
9791,9792.0,CA-2015-127166,21/05/2015,23/05/2015,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-EN-10003134,Office Supplies,Envelopes,Staple envelope,56.0640
9795,9796.0,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797.0,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680

In [ ]:
data['Order Date'] = pd.to_datetime(data['Order Date'], format='%d/%m/%Y')
(data['Order Date'].max()-data['Order Date'].min()).days

1457

In [ ]:
data['Order Date'] = pd.to_datetime(data['Order Date'], format='%d/%m/%Y')
unique_days = data['Order Date'].nunique()
unique_weeks = unique_days // 7
print("Nombre de jours :", unique_days, "Nombre de semaines :", unique_weeks)

Nombre de jours : 1004 Nombre de semaines : 143

In [ ]:
print("Modes d'expédition :", data['Ship Mode'].nunique())#donn nmbr des modes unique ms uniquedonnes les nom d modes

Modes d'expédition : 4

In [ ]:

most_requests_customer = data['Customer ID'].value_counts().idxmax()
most_requests_count = data['Customer ID'].value_counts().max()

spending_per_customer = data.groupby('Customer ID')['Sales'].sum()
highest_spender_customer = spending_per_customer.idxmax()
highest_spender_amount = spending_per_customer.max()

data['Order Date'] = pd.to_datetime(data['Order Date'],format='%d/%m/%Y')
data['Ship Date'] = pd.to_datetime(data['Ship Date'],format='%d/%m/%Y')
data['Delivery Time'] = (data['Ship Date'] - data['Order Date']).dt.days


delivery_care_per_customer = data.groupby('Customer ID')['Delivery Time'].mean()
most_delivery_care_customer = delivery_care_per_customer.idxmin()  # Use idxmin for minimum delivery time
lowest_delivery_time = delivery_care_per_customer.min()


total_customers = data['Customer ID'].nunique()

top_customers = {most_requests_customer, highest_spender_customer, most_delivery_care_customer}
unique_top_customers_count = len(top_customers)

top_customers_proportion = unique_top_customers_count / total_customers

print(f"Customer with Most Requests: {most_requests_customer} ({most_requests_count} requests)")
print(f"Highest Spender Customer: {highest_spender_customer} (${highest_spender_amount})")
print(f"Customer Who Cares Most About Deliveries: {most_delivery_care_customer} (Avg. Delivery Time: {lowest_delivery_time} days)")
print(f"Proportion of Unique Top Customers Among Total Customers: {top_customers_proportion:.2%}")

Customer with Most Requests: WB-21850 (35 requests)
Highest Spender Customer: SM-20320 ($25043.05)
Customer Who Cares Most About Deliveries: SG-20080 (Avg. Delivery Time: 0.7272727272727273 days)
Proportion of Unique Top Customers Among Total Customers: 0.38%

'BM-11650'

In [ ]:
import pandas as pd

data['Order Date'] = pd.to_datetime(data['Order Date'])

data['Order Month'] = data['Order Date'].dt.to_period('M')
product_demand = data.groupby(['Product ID', 'Order Month']).size().unstack(fill_value=0)

high_demand_products = product_demand.sum(axis=1).sort_values(ascending=False).head(10)

seasonal_demand_patterns = product_demand.loc[high_demand_products.index].transpose()

if 'Quality Feedback' in data.columns:
    low_quality_feedback = data[data['Quality Feedback'] < 3].groupby('Product ID').size().sort_values(ascending=False).head(10)

print("Top 10 High-Demand Products:\n", high_demand_products)
print("\nDemand Patterns Over Time for High-Demand Products:\n", seasonal_demand_patterns)

if 'Quality Feedback' in data.columns:
    print("\nProducts with Most Low Quality Feedback (Potential Canning Issues):\n", low_quality_feedback)

Top 10 High-Demand Products:
 Product ID
OFF-PA-10001970    19
TEC-AC-10003832    18
FUR-FU-10004270    16
TEC-AC-10003628    15
FUR-CH-10002647    15
TEC-AC-10002049    15
FUR-CH-10002880    14
OFF-BI-10001524    14
OFF-PA-10002377    14
OFF-BI-10004632    14
dtype: int64

Demand Patterns Over Time for High-Demand Products:
 Product ID   OFF-PA-10001970  TEC-AC-10003832  FUR-FU-10004270  \
Order Month
2015-01                    0                0                0
2015-02                    0                0                0
2015-03                    0                0                1
2015-04                    0                0                0
2015-05                    0                0                0
2015-06                    0                0                0
2015-07                    1                0                0
2015-08                    0                0                0
2015-09                    0                0                1
2015-10                    0                0                1
2015-11                    0                2                0
2015-12                    0                0                1
2016-01                    0                0                0
2016-02                    1                0                0
2016-03                    0                0                0
2016-04                    0                0                0
2016-05                    0                0                0
2016-06                    0                0                0
2016-07                    0                0                0
2016-08                    0                0                1
2016-09                    3                1                0
2016-10                    0                0                0
2016-11                    0                0                0
2016-12                    1                0                2
2017-01                    0                0                1
2017-02                    0                0                0
2017-03                    0                1                1
2017-04                    1                0                0
2017-05                    0                3                1
2017-06                    1                0                1
2017-07                    0                0                0
2017-08                    0                0                0
2017-09                    2                1                0
2017-10                    1                1                0
2017-11                    1                1                1
2017-12                    0                1                0
2018-01                    1                0                0
2018-02                    1                0                1
2018-03                    0                0                0
2018-04                    0                1                0
2018-05                    0                0                0
2018-06                    1                3                0
2018-07                    1                1                0
2018-08                    1                0                0
2018-09                    0                0                1
2018-10                    0                0                0
2018-11                    0                1                1
2018-12                    2                1                1

Product ID   TEC-AC-10003628  FUR-CH-10002647  TEC-AC-10002049  \
Order Month
2015-01                    1                0                0
2015-02                    0                0                0
2015-03                    0                0                0
2015-04                    0                0                0
2015-05                    0                0                0
2015-06                    1                1                0
2015-07                    0                1                0
2015-08                    0                0                0
2015-09                    1                0                0
2015-10                    0                0                0
2015-11                    0                0                0
2015-12                    3                0                1
2016-01                    0                0                0
2016-02                    0                0                0
2016-03                    0                1                0
2016-04                    0                0                0
2016-05                    1                1                0
2016-06                    0                0                0
2016-07                    1                0                0
2016-08                    0                0                0
2016-09                    0                0                1
2016-10                    0                0                1
2016-11                    0                1                1
2016-12                    0                1                3
2017-01                    1                0                1
2017-02                    2                0                0
2017-03                    0                1                0
2017-04                    0                0                0
2017-05                    0                0                0
2017-06                    0                0                0
2017-07                    0                0                0
2017-08                    0                0                0
2017-09                    0                2                1
2017-10                    0                0                0
2017-11                    0                1                1
2017-12                    0                1                0
2018-01                    1                0                1
2018-02                    0                0                0
2018-03                    0                0                0
2018-04                    0                0                0
2018-05                    0                1                0
2018-06                    0                1                0
2018-07                    1                1                1
2018-08                    0                0                1
2018-09                    2                0                0
2018-10                    0                0                2
2018-11                    0                0                0
2018-12                    0                1                0

Product ID   FUR-CH-10002880  OFF-BI-10001524  OFF-PA-10002377  \
Order Month
2015-01                    0                0                0
2015-02                    0                0                0
2015-03                    0                0                0
2015-04                    0                0                0
2015-05                    0                0                0
2015-06                    0                0                0
2015-07                    1                1                0
2015-08                    0                0                1
2015-09                    0                0                0
2015-10                    2                0                0
2015-11                    0                0                0
2015-12                    0                0                0
2016-01                    0                0                0
2016-02                    0                0                1
2016-03                    0                0                0
2016-04                    0                1                1
2016-05                    1                0                0
2016-06                    0                0                0
2016-07                    0                1                0
2016-08                    0                0                0
2016-09                    0                0                1
2016-10                    0                0                0
2016-11                    2                2                0
2016-12                    0                0                1
2017-01                    0                0                0
2017-02                    0                0                0
2017-03                    1                0                0
2017-04                    1                0                1
2017-05                    0                0                0
2017-06                    0                1                0
2017-07                    0                0                0
2017-08                    0                1                0
2017-09                    2                0                1
2017-10                    0                0                1
2017-11                    0                1                0
2017-12                    0                1                0
2018-01                    0                0                0
2018-02                    1                0                1
2018-03                    1                0                1
2018-04                    0                0                0
2018-05                    0                0                0
2018-06                    0                0                1
2018-07                    0                1                0
2018-08                    0                0                0
2018-09                    0                0                1
2018-10                    1                0                1
2018-11                    0                1                1
2018-12                    1                3                0

Product ID   OFF-BI-10004632
Order Month
2015-01                    1
2015-02                    0
2015-03                    0
2015-04                    0
2015-05                    0
2015-06                    0
2015-07                    0
2015-08                    0
2015-09                    1
2015-10                    0
2015-11                    0
2015-12                    1
2016-01                    0
2016-02                    0
2016-03                    0
2016-04                    0
2016-05                    0
2016-06                    0
2016-07                    0
2016-08                    1
2016-09                    0
2016-10                    0
2016-11                    0
2016-12                    1
2017-01                    0
2017-02                    0
2017-03                    1
2017-04                    0
2017-05                    0
2017-06                    0
2017-07                    0
2017-08                    0
2017-09                    0
2017-10                    0
2017-11                    1
2017-12                    0
2018-01                    1
2018-02                    1
2018-03                    1
2018-04                    0
2018-05                    1
2018-06                    1
2018-07                    0
2018-08                    0
2018-09                    1
2018-10                    0
2018-11                    0
2018-12                    1

0.13280212483399734

In [ ]:
data['Ship Date'] = pd.to_datetime(data['Ship Date'],format='%d/%m/%Y')
data['Order-Ship Duration'] = (data['Ship Date'] - data['Order Date']).dt.days
print(data['Order-Ship Duration'])

0       3
1       3
2       4
3       7
4       7
       ..
4817    5
4818    5
4819    6
4820    4
4821    4
Name: Order-Ship Duration, Length: 4822, dtype: int64

In [ ]:
category_sales = data.groupby('Category')['Sales'].sum()
category_sales.idxmax()

'Technology'

In [ ]:
segment_analysis = data.groupby('Segment')['Sales'].sum()
print("Segment avec le plus de ventes :", segment_analysis.idxmax())

Segment avec le plus de ventes : Consumer

In [ ]:
data.groupby(['Order Date', 'Product Name']).size()

Order Date  Product Name
2015-01-04  Avery 508                                                             1
            GBC Standard Plastic Binding Systems Combs                            1
            SAFCO Boltless Steel Shelving                                         1
2015-01-05  Avery Hi-Liter EverBold Pen Style Fluorescent Highlighters, 4/Pack    1
2015-01-09  Memorex Micro Travel Drive 8 GB                                       1
                                                                                 ..
2018-12-30  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl                       1
            Eureka The Boss Plus 12-Amp Hard Box Upright Vacuum, Red              1
            GBC Binding covers                                                    1
            Gear Head AU3700S Headset                                             1
            Wilson Jones Legal Size Ring Binders                                  1
Length: 4809, dtype: int64

In [ ]:
X = '2018-01-01'
Y = '2018-12-31'

period_data = data[(data['Order Date'] >= X) & (data['Order Date'] <= Y)]
period_average_sales = period_data['Sales'].mean()
print("Moyenne des ventes sur la période :", period_average_sales)

Moyenne des ventes sur la période : 0.01005490764242478

In [ ]:
Y = 500
low_sales_data = data[data['Sales'] < Y].groupby('City').size()
print(low_sales_data)

City
Akron          15
Albuquerque    10
Alexandria     15
Allen           4
Allentown       2
               ..
Woodstock       3
Woonsocket      1
Yonkers         7
York            3
Yucaipa         1
Length: 420, dtype: int64

In [ ]:
data[(data['City'] == 'X') & (data['Sales'] > Y)].shape[0]

0

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,sale interest,Normalized Sales,Order-Ship Duration,Quantity
0,1,CA-2017-152156,2017-11-08 00:00:00,2017-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,0.011571,1.0,0.011571,3.0,1
1,2,CA-2017-152156,2017-11-08 00:00:00,2017-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",0.032332,1.0,0.032332,3.0,1
2,3,CA-2017-138688,2017-06-12 00:00:00,2017-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,0.000646,1.0,0.000646,4.0,1
3,4,US-2016-108966,2016-10-11 00:00:00,2016-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,0.042299,1.0,0.042299,7.0,1
4,5,US-2016-108966,2016-10-11 00:00:00,2016-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,0.000988,1.0,0.000988,7.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14617,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798000,NaN,NaN,NaN,1
14618,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368000,NaN,NaN,NaN,1
14619,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188000,NaN,NaN,NaN,1
14620,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376000,NaN,NaN,NaN,1
14621,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384000,NaN,NaN,NaN,1

In [ ]:
daily_sales_diff = data.groupby('Order Date')['Sales'].sum().diff()
data.resample('W', on='Order Date')['Sales'].sum().diff()

Order Date
2015-01-04         NaN
2015-01-11   -0.007209
2015-01-18    0.095336
2015-01-25   -0.018717
2015-02-01    0.012164
                ...
2018-12-02    0.056625
2018-12-09   -0.213295
2018-12-16   -0.220597
2018-12-23    0.343622
2018-12-30   -0.173107
Freq: W-SUN, Name: Sales, Length: 209, dtype: float64

In [ ]:
new_data = pd.read_csv('/content/train.csv')
data = pd.concat([data, new_data]).reset_index(drop=True)

In [ ]:
data['Ship Mode'] = pd.to_datetime(data['Ship Mode'],format='%d/%m/%Y')
data['Order Date'] = pd.to_datetime(data['Order Date'],format='%d/%m/%Y')
def sameday_dat():

    sameday = data[data['Ship Mode'] == data['Order Date']]


    if sameday.empty:
        return "Aucun produit n'a été livré le jour même de la commande etait cmnd."
    else:

        return sameday['Product Name']


sameday_products = sameday_dat()
print(sameday_products)
print("\nLes produits à vérifier (commandés mais non livrés le jour même) :")
non_sameday_products = data[~data.index.isin(sameday_products.index)]['Product Name'].unique()
print("les produit qui'll faux verifier :",len(non_sameday_products))

366     Wilson Jones “Snap” Scratch Pad Binder Tool fo...
367                                        Staple remover
368                              Pizazz Global Quick File
369     Atlantic Metals Mobile 3-Shelf Bookcases, Cust...
657         Global Troy Executive Leather Low-Back Tilter
                              ...
9697       DAX Charcoal/Nickel-Tone Document Frame, 5 x 7
9745    Hon Practical Foundations 30 x 60 Training Tab...
9746         Hon 61000 Series Interactive Training Tables
9772                                           Xerox 1925
9786                  Global Stack Chair with Arms, Black
Name: Product Name, Length: 514, dtype: object

Les produits à vérifier (commandés mais non livrés le jour même) :
les produit qui'll faux verifier : 1841